### PR TITLE
Changes for working with the submissions controller logic

### PR DESCRIPTION
**Pull request by aselbie**

### CODE REVIEW

**Comment by aselbie** [comment]
Build needs schema updates to work properly: https://github.com/appirio-tech/api-schemas/pull/6

**Comment by samsep** [comment]
LGTM

**Comment by vietnogi** [comment]
I thought we're getting together once the controller are done to discuss the application layer with lugging?

**Comment by aselbie** [comment]
Nothing has been communicated to me, so I've just been trying to make my best guess. I'm happy to change any of this later. Do you mind if we merge this now so that the submission controller changes can pass?

**Pull request closed without merging**
